name: tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.0", "5.1", "5.2"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update tools
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4
      - name: Install Project
        run: |
          poetry install
          poetry add django==${{ matrix.django-version }}
      - name: Run CI Tests
        run: |
          make tests
  publish-testpypi:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Build package
        run: poetry build
      - name: Publish to TestPyPI
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.POETRY_PYPI_TOKEN_TESTPYPI }}
          repository_url: https://test.pypi.org/legacy/
